import{loadData,photoURL,priceText}from './store.js';
const $=id=>document.getElementById(id),dialog=$('detail');let data,returnFocus,closing=false,activeId;const sections=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function fallback(){const e=el('div',undefined,'placeholder');e.innerHTML='<svg viewBox="0 0 140 210" fill="none" aria-hidden="true"><path d="M20 25H120L70 100L20 25Z M70 100V180 M40 184H100" stroke="currentColor" stroke-width="1.3"/><path d="M31 43H109" stroke="currentColor" stroke-opacity=".4"/><ellipse cx="70" cy="190" rx="45" ry="5" fill="currentColor" opacity=".06"/></svg>';e.append(el('small','Originalfoto folgt'));return e;}
function visual(d,eager=false){const e=el('div',undefined,'visual'),url=photoURL(d.photo);if(url){const i=el('img');i.src=url;i.alt=d.photoAlt||d.name;i.loading=eager?'eager':'lazy';i.decoding='async';i.addEventListener('load',()=>{try{const c=document.createElement('canvas');c.width=c.height=16;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(i,0,0,16,16);const px=ctx.getImageData(0,0,16,16).data;let rgb=[0,0,0],n=0;for(let k=0;k<px.length;k+=4){if(px[k+3]>128){rgb=rgb.map((v,j)=>v+px[k+j]);n++;}}if(n){d.palette=['#'+rgb.map(v=>Math.round(v/n*.55).toString(16).padStart(2,'0')).join('')];if(sections.find(s=>s.id===activeId)?.drinks[sections.find(s=>s.id===activeId)?.index]?.id===d.id)tone(d);}}catch{}},{once:true});i.addEventListener('error',()=>i.replaceWith(fallback()),{once:true});e.append(i);}else e.append(fallback());return e;}
let layer=false;function tone(d){const t=d.palette?.[0];const color=/^#[0-9a-f]{6}$/i.test(t)?t:'#704329';layer=!layer;const a=$(layer?'glowA':'glowB'),b=$(layer?'glowB':'glowA');a.style.setProperty('--tone',color);a.style.opacity='.75';b.style.opacity='0';}
function selectCategory(id){
 if(activeId===id)return;activeId=id;
 const nav=$('categories');for(const b of nav.children){const active=b.dataset.id===id;b.setAttribute('aria-pressed',active);if(active){const nr=nav.getBoundingClientRect(),br=b.getBoundingClientRect();nav.scrollTo({left:nav.scrollLeft+br.left-nr.left-(nav.clientWidth-br.width)/2,behavior:reduced?'instant':'smooth'});}}
 const s=sections.find(s=>s.id===id);if(s?.drinks[s.index])tone(s.drinks[s.index]);
}
function buildCategory(c){
 const section=el('section',undefined,'category-section');section.id=c.id;
 const title=el('h2',c.name);title.id=c.id+'-title';section.setAttribute('aria-labelledby',title.id);
 const drinks=data.drinks.filter(d=>d.categoryId===c.id&&(d.active||data.settings?.unavailableMode!=='hide')).sort((a,b)=>a.order-b.order);
 const line=el('div',undefined,'sectionline');line.append(title,el('span',`${drinks.length} ${drinks.length===1?'Drink':'Drinks'}`));
 const rail=el('div',undefined,'rail');rail.setAttribute('aria-label','Drinks · '+c.name);
 const navigation=el('div',undefined,'navigation'),prev=el('button','←'),next=el('button','→'),position=el('span');prev.setAttribute('aria-label','Vorheriger Drink · '+c.name);next.setAttribute('aria-label','Nächster Drink · '+c.name);position.setAttribute('aria-live','polite');navigation.append(prev,position,next);
 const state={id:c.id,section,rail,drinks,index:0};sections.push(state);
 function activate(i){state.index=i;[...rail.children].forEach((b,j)=>b.classList.toggle('current',j===i));position.textContent=drinks.length?`${i+1} / ${drinks.length}`:'0 / 0';prev.disabled=!i;next.disabled=i>=drinks.length-1;if(activeId===c.id&&drinks[i])tone(drinks[i]);}
 drinks.forEach((d,i)=>{const b=el('button',undefined,'drink');b.type='button';b.setAttribute('aria-label',d.name+', '+priceText(d));b.append(visual(d,sections.length===1&&i===0),el('h3',d.name),el('div',priceText(d),'price'));if(!d.active)b.append(el('p','Derzeit nicht verfügbar','badge'));b.append(el('p','ENTDECKEN ↗','hint'));b.onclick=()=>open(d,b);rail.append(b);});
 function move(step){const i=Math.max(0,Math.min(drinks.length-1,state.index+step));const card=rail.children[i];if(card)rail.scrollTo({left:card.offsetLeft-rail.offsetLeft-(rail.clientWidth-card.offsetWidth)/2,behavior:reduced?'instant':'smooth'});}
 prev.onclick=()=>move(-1);next.onclick=()=>move(1);rail.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(e.key==='ArrowRight'?1:-1);}});
 // Native two-axis touch scrolling: no gesture interception or vertical preventDefault.
 const observer=new IntersectionObserver(entries=>{const best=entries.filter(e=>e.isIntersecting&&e.intersectionRatio>=.6).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(best)activate([...rail.children].indexOf(best.target));},{root:rail,threshold:[.6,.8]});[...rail.children].forEach(b=>observer.observe(b));
 activate(0);section.append(line,rail,navigation,el('p',drinks.length?'↔ Drinks entdecken · ↓ Weitere Kategorien':'Derzeit keine verfügbaren Drinks','section-hint'));$('sections').append(section);
 const tab=el('button',c.name);tab.dataset.id=c.id;tab.onclick=()=>section.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});$('categories').append(tab);
}
let queued=false;function trackSection(){if(queued||dialog.open)return;queued=true;requestAnimationFrame(()=>{queued=false;const anchor=$('categories').getBoundingClientRect().bottom+90;let current=sections[0];for(const s of sections){if(s.section.getBoundingClientRect().top<=anchor)current=s;}if(current)selectCategory(current.id);});}
window.addEventListener('scroll',trackSection,{passive:true});window.addEventListener('resize',trackSection);
function open(d,b){if(closing)return;returnFocus=b;$('detailImage').replaceChildren(visual(d,true));$('detailName').textContent=d.name;$('detailCategory').textContent=data.categories.find(c=>c.id===d.categoryId)?.name;$('detailPrice').textContent=priceText(d);$('detailDescription').textContent=d.description||'';$('detailDescription').hidden=!d.description;$('availability').textContent=d.active?'':'Derzeit nicht verfügbar';$('ingredients').replaceChildren(...d.ingredients.map(x=>el('li',x)));$('recipeNote').textContent=d.notes||'';$('extras').replaceChildren();for(const [label,value]of [['Glas',d.glass],['Garnitur',d.garnish],['Allergene',d.allergens?.join(', ')],['Alkohol',d.alcoholContent]])if(value)$('extras').append(el('dt',label),el('dd',String(value)));dialog.showModal();document.body.style.overflow='hidden';requestAnimationFrame(()=>dialog.classList.add('open'));$('close').focus();}
function close(){if(closing)return;closing=true;dialog.classList.remove('open');setTimeout(()=>{dialog.close();document.body.style.overflow='';returnFocus?.focus({preventScroll:true});closing=false;trackSection();},reduced?0:300);}$('close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
try{data=await loadData({draft:new URLSearchParams(location.search).has('preview')});for(const c of [...data.categories].sort((a,b)=>a.order-b.order))buildCategory(c);$('status').hidden=true;trackSection();}catch(e){$('status').textContent=e.message+' Bitte lade die Seite erneut.';}
